### ISSUE TITLE
Pressing F10 while ImGui flimmers crashes the program.

### ISSUE THREAD

**Issue by DanielFredriksson** [BTH-StoraSpel-DXR/SPLASH#344] opened 2019-10-25 13:53 UTC
Run enough applications on the same computer (not on release) until the flimmer appears. When in-game, press F10 and that client will crash.

**Comment by Piratkopia13** [comment] 2019-10-28 12:13
imgui flimmer is caused by the screen space renderer. Investigation in progress 🕵

**Comment by Piratkopia13** [comment] 2019-10-28 13:49
should be fixed in pr #360

**Comment by Piratkopia13** [comment] 2019-10-29 07:55
if anyone still gets this crash - please post a screenshot of the crash with callstack here

**Closed** 2019-10-29 14:16 UTC
Labels: Crash, bug, question
